name: Test PullRequest

on:
  push:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  xcode_text:
    name: Xcode Test
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run all tests
        run: xcodebuild test -project xcresult-summary-app.xcodeproj -scheme xcresult-summary-app -destination 'platform=iOS Simulator,name=iPhone 16' -resultBundlePath "./build/test_results/XCTest.xcresult"
      - name: Generate Test Summary
        uses: tsoejima/xcresult-summary@v1.0.9
        with:
          xcresult-path: './build/test_results/XCTest.xcresult'
        if: always()
